name: Release

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: gitea.home
          username: ci-account
          password: ${{ secrets.CI_PASSWORD }}
      - name: Run +docker target
        run: earthly --ci --push +docker